title: Amanda Flores
logo: https://studentsloyola-my.sharepoint.com/:x:/g/personal/avfloresgonzalez_loyola_edu/IQC9J-zgDCe4Sr871qBtUpa2AdX54NesaKnde4seMEWBpxo?e=8gaeSC
#description: text below image
#show_downloads: true
theme: jekyll-theme-midnight
